[package]
name = "api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dex = { path = "../dex" }
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "6206a46" }
